### ISSUE TITLE
VNC Luanch Stuck

### ISSUE THREAD

**Issue by ericxu233** [junhaoliao/iCtrl#24]
![image](https://github.com/junhaoliao/iCtrl/assets/60671484/d25b4b19-2042-4139-9b6b-8ea94947a4eb)
Any ideas on how to resolve this issue? Already tried to uninstall an resinstall.

**Comment by ericxu233** [comment]
Nevermind, solved the issue by just killing the session tab.

**Comment by junhaoliao** [comment]
Were you connecting to a EECG host? I think the issue is a known one, where iCtrl might mistakenly think a long listening VNC port 5900 is opened on the machine. It should have been fixed in this repository. Supposedly Web version users would be able to use the latest versions with bug fixes, but as you know iCtrl Web has been temporally (or permanently) shutdown due to concerns from school lab managers. 

I will release a new desktop version if I have the time to build it. In the meantime, let me know if you know somebody who is interested in maintaining the application.
