### ISSUE TITLE
SSH Authentication stuck

### ISSUE THREAD

**Issue by briefs4skin** [junhaoliao/iCtrl#26]
**Describe the bug**
Stuck at the SSH Authentication stage.
The change machine keeps loading.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/junhaoliao/iCtrl/assets/139562018/a248537b-9852-46cd-8861-d9da109b666a)
![image](https://github.com/junhaoliao/iCtrl/assets/139562018/986146f8-553d-442f-9a21-4555a5196d29)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by junhaoliao** [comment]
Hello, may i know if any other convention SSH clients (e.g., OpenSSH, PuTTY) are working for you on the same host? Which host are you connecting to?

**Comment by briefs4skin** [comment]
The issue is gone after I deleted the whole section and created a new VNC section

**Comment by junhaoliao** [comment]
Likely the host you were trying to connect to was down.

If it happens again, it will greatly help if you can share more details (e.g., your OS platform, target hostname, etc.).

**Comment by briefs4skin** [comment]
The host was 'ug62.eecg.toronto.edu', and I am using Win10. After I deleted the whole section and created a brand new section with the same host, everything worked again. So I doubt if the host was down.

**Comment by junhaoliao** [comment]
Some code changes might have fixed the issue but I haven't release a new desktop app version since a year ago. 

I'm unable to release new versions for macOS as I just found my subscription expired last year in May lol. Just spent another $120 to find their membership still requires human approval so that may take another few days. The Windows version is usually released together with the mac version to avoid confusions to the iCtrl version upgrade system. 

In the version after the upcoming release, to help investigate issues like this, I'll add logging support as soon as the CLP IR logging library is ready on Windows. https://github.com/y-scope/clp-ffi-py/pull/56

The Windows certificate is also expiring next February which will cost another few hundred bucks. I have no problem keeping paying fees to avoid downloads getting blocked by "anti-virus" filters and platform vendors; however, having this project open for uoft students to collaborate and gain some experience is something I want to achieve, as I personally have benefited from doing so. Let me know if you, your friends, or their friends are interested in maintaining iCtrl (code-wise) to keep it open and free.
